@startuml
remove @unlinked
package "service1" as service1 #line.dotted;text:gray {
  package "api" as service1.api #line.dotted;text:gray {
    package "http" as service1.api.http #line.dotted;text:gray {
      component mainController as mainController
    }
    package "ws" as service1.api.ws #line.dotted;text:gray {
      component eventsHandler as eventsHandler
    }
  }
  package "db" as service1.db #line.dotted;text:gray {
    package "jpa" as service1.db.jpa #line.dotted;text:gray {
      component simpleEntityRepository as simpleEntityRepository
      component userRepository as userRepository
    }
    package "mongo" as service1.db.mongo #line.dotted;text:gray {
      component documentRepository as documentRepository
    }
  }
  package "service" as service1.service #line.dotted;text:gray {
    component coreService as coreService
    package "external" as service1.service.external #line.dotted;text:gray {
      package "jms" as service1.service.external.jms #line.dotted;text:gray {
        component jmsQueueListener as jmsQueueListener
        component jmsQueueService as jmsQueueService
      }
      package "rest" as service1.service.external.rest #line.dotted;text:gray {
        component service2FeignClient as service2FeignClient
        component service2LegacyImpl as service2LegacyImpl
        component standaloneService2Api as standaloneService2Api
      }
      package "ws" as service1.service.external.ws #line.dotted;text:gray {
        component service2StreamClientImpl as service2StreamClientImpl
      }
    }
    package "scheduled" as service1.service.scheduled #line.dotted;text:gray {
      component periodUpdateService as periodUpdateService
    }
  }
}
coreService ..> documentRepository
coreService ..> jmsQueueService
coreService ..> service2FeignClient
coreService ..> service2LegacyImpl
coreService ..> simpleEntityRepository
coreService ..> standaloneService2Api
jmsQueueListener ..> coreService
mainController ..> coreService
periodUpdateService ..> jmsQueueService
periodUpdateService ..> service2FeignClient
periodUpdateService ..> userRepository
cloud "input" as input #line.dotted;line:gray; {
  rectangle "http" as input.http {
    frame "/api/v1" as input.http..api.v1 #line.dotted;text:gray {
      collections "<#transparent,transparent>|<r>*: | |\n\
<#transparent,transparent>|<r>GET: |/load/{id}|\n\
<#transparent,transparent>|<r>POST: |/put/{id}|" as input.http..api.v1.interfaces
      input.http..api.v1.interfaces 0)....> mainController
    }
  }
  rectangle "web socket" as input.websocket {
    frame "eventsHandler" as input.websocket.eventsHandler.eventsHandler.interfaces #line.dotted;text:gray {
      interface "/events" as in.eventsHandler.in.ws..events
      in.eventsHandler.in.ws..events )....> eventsHandler
    }
  }
  queue "jms" as input.jms {
    frame "jmsQueueListener" as input.jms.jmsQueueListener.jmsQueueListener.interfaces #line.dotted;text:gray {
      collections "<#transparent,transparent>|queue1|\n\
<#transparent,transparent>|queue2|" as input.jms.jmsQueueListener.interfaces
      input.jms.jmsQueueListener.interfaces 0)....> jmsQueueListener
    }
    frame "jmsQueueService" as input.jms.jmsQueueService.jmsQueueService.interfaces #line.dotted;text:gray {
      interface "jmsTemplate-default" as in.jmsQueueService.jmsTemplate.default.in
      in.jmsQueueService.jmsTemplate.default.in )....> jmsQueueService
    }
  }
}
cloud "output" as output #line.dotted;line:gray; {
  rectangle "http" as output.http {
    frame "http://service2" as output.http.http...service2 #line.dotted;text:gray {
      collections "<#transparent,transparent>|<r>GET: | |\n\
<#transparent,transparent>|<r>GET: |/load-deprecated/{Service2LegacyImpl.getDeprecated({id})}|\n\
<#transparent,transparent>|<r>GET: |/load/{Integer.valueOf({{Integer.valueOf({MainController.save({id})})}.intValue()}+1)}|\n\
<#transparent,transparent>|<r>GET: |/load2/{Integer.valueOf(-{{Integer.valueOf({MainController.save({id})})}.intValue()}+2)}|" as output.http.http...service2.interfaces
      service2LegacyImpl ....(0 output.http.http...service2.interfaces
      frame "/{id}" as output.http.http...service2...id. #line.dotted;text:gray {
        collections "<#transparent,transparent>|<r>GET: | |\n\
<#transparent,transparent>|<r>GET: |/unused|" as output.http.http...service2...id..interfaces
        service2FeignClient ....(0 output.http.http...service2...id..interfaces
      }
    }
    frame "/standalone-service2/{id}" as output.http..standalone.service2..id. #line.dotted;text:gray {
      collections "<#transparent,transparent>|<r>GET: | |\n\
<#transparent,transparent>|<r>GET: |/unused|" as output.http..standalone.service2..id..interfaces
      standaloneService2Api ....(0 output.http..standalone.service2..id..interfaces
    }
  }
  rectangle "web socket" as output.websocket {
    frame "service2StreamClientImpl" as output.websocket.service2StreamClientImpl.service2StreamClientImpl.interfaces #line.dotted;text:gray {
      collections "<#transparent,transparent>|ws://currentURI-method|\n\
<#transparent,transparent>|ws://currentURI-supplier|\n\
<#transparent,transparent>|ws://defaultURI-static|\n\
<#transparent,transparent>|ws://service-property-injected|\n\
<#transparent,transparent>|ws://service-template|\n\
<#transparent,transparent>|ws://service-template/{id}/|\n\
<#transparent,transparent>|ws://service2|\n\
<#transparent,transparent>|ws://service2-value-inject|\n\
<#transparent,transparent>|ws://service3|" as output.websocket.service2StreamClientImpl.interfaces
      service2StreamClientImpl ....(0 output.websocket.service2StreamClientImpl.interfaces
    }
  }
  queue "jms" as output.jms {
    frame "jmsQueueService" as output.jms.jmsQueueService.jmsQueueService.interfaces #line.dotted;text:gray {
      collections "<#transparent,transparent>|jms-private-queue|\n\
<#transparent,transparent>|jmsQueue2|\n\
<#transparent,transparent>|jmsQueueEvents|\n\
<#transparent,transparent>|jmsQueueEvents2|\n\
<#transparent,transparent>|jmsQueueEvents3|\n\
<#transparent,transparent>|jmsQueue{CoreService.lambda$makeAll$0({i})}|" as output.jms.jmsQueueService.interfaces
      jmsQueueService ....> output.jms.jmsQueueService.interfaces
    }
  }
}
cloud "internal" as internal #line.dotted;line:gray; {
  database "storage" as internal.storage {
    folder "jpa.model" as internal.storage.jpa.model #line.dotted;line:gray; {
      collections "<#transparent,transparent>|=Entity |=Table|\n\
<#transparent,transparent>|SimpleEntity |<i>simple_entity|\n\
<#transparent,transparent>|UserEntity |<i>auth.user|" as internal.storage.jpa.model.interfaces
      internal.storage.jpa.model.interfaces .. simpleEntityRepository
      internal.storage.jpa.model.interfaces .. userRepository
    }
    folder "mongo.model" as internal.storage.mongo.model #line.dotted;line:gray; {
      entity "DocumentEntity" as internal.mongo.classservice1.db.mongo.model.DocumentEntity..documentEntity.
      note "collection: documentEntity" as internal.mongo.classservice1.db.mongo.model.DocumentEntity..documentEntity..table_name
      internal.mongo.classservice1.db.mongo.model.DocumentEntity..documentEntity..table_name .. internal.mongo.classservice1.db.mongo.model.DocumentEntity..documentEntity.
      internal.mongo.classservice1.db.mongo.model.DocumentEntity..documentEntity. .. documentRepository
    }
  }
  rectangle "scheduler" as internal.scheduler {
    collections "<#transparent,transparent>|cron(* * * 2 * *) |fixedRate(12min)|\n\
<#transparent,transparent>|cron(* * * 3 * *) |fixedRate(1d1h)|\n\
<#transparent,transparent>|cron(* * * 4 * *) |fixedRate(21h)|\n\
<#transparent,transparent>|cron(* * 1 * * *) | |\n\
<#transparent,transparent>|fixedDelay(1h1min1sec500msec) | |\n\
<#transparent,transparent>|fixedDelay(1sec) | |\n\
<#transparent,transparent>|fixedDelay(2sec) | |\n\
<#transparent,transparent>|fixedDelay(3sec) | |\n\
<#transparent,transparent>|fixedDelay(4sec) | |\n\
<#transparent,transparent>|fixedDelay(5sec) | |" as internal.scheduler.interfaces
    internal.scheduler.interfaces .. periodUpdateService
  }
}
@enduml
