@startuml
package "api" as api {
  package "http" as api.http {
    [mainController] as mainController
  }
}
package "service" as service {
  package "external" as service.external {
    [coreService] as coreService
    package "jms" as service.external.jms {
      [jmsQueue1Listener] as jmsQueue1Listener
    }
    package "rest" as service.external.rest {
      [service2LegacyImpl] as service2LegacyImpl
      [standaloneService2Api] as standaloneService2Api
      [service2FeignClient] as service2FeignClient
    }
    package "ws" as service.external.ws {
      [service2StreamClientImpl] as service2StreamClientImpl
    }
  }
}
package "internal" as internal {
  package "ws" as internal.ws {
    package "EventsHandler" as internal.ws.EventsHandler {
      [eventsHandler] as eventsHandler
    }
  }
}
mainController ..> coreService
coreService ..> service2FeignClient
coreService ..> service2LegacyImpl
coreService ..> standaloneService2Api
jmsQueue1Listener ..> coreService
service2LegacyImpl ..> restTemplate
service2StreamClientImpl ..> webSocketClient
eventsHandler ..> webSocketConfig
rectangle "in" as in {
  cloud "jms" as in.jms {
    queue "jmsQueue1Listener" as in.jmsQueue1Listener {
      interface "queue1" as jmsQueue1Listener.in.jms.queue1
      jmsQueue1Listener.in.jms.queue1 )..> jmsQueue1Listener
      interface "queue2" as jmsQueue1Listener.in.jms.queue2
      jmsQueue1Listener.in.jms.queue2 )..> jmsQueue1Listener
    }
  }
  cloud "http" as in.http {
    interface "GET:/api/v1/req" as mainController.in.http.GET..api.v1.req
    mainController.in.http.GET..api.v1.req )..> mainController
    interface "*:/api/v1/" as mainController.in.http...api.v1.
    mainController.in.http...api.v1. )..> mainController
  }
}
rectangle "out" as out {
  cloud "http" as out.http {
    cloud "standalone-service2" as out.standalone.service2 {
      interface "GET:/{id}" as standaloneService2Api.out.http.GET..id
      standaloneService2Api ..( standaloneService2Api.out.http.GET..id
    }
    cloud "http://service2" as out.http...service2 {
      interface "GET:/{id}" as service2FeignClient.out.http.GET..id
      service2FeignClient ..( service2FeignClient.out.http.GET..id
    }
  }
}
@enduml
